from .dashboard_ui1 import Ui_dashboard
from .journee1_ui1 import Ui_DayView
from .cree_journee_ui1 import Ui_CreateJourneeWidget
from .create_exercices_ui import Ui_ExerciseCreator
from .afficher_exercice_valide import Ui_AvailableExercisesDialog
from .add_exercice_available_ui import Ui_AddAvailableMovementWidget
from .create_food_ui import Ui_AddFoodWidget
from . afficher_nourriture_valide_ui import Ui_AvailableNourritureDialog
from .add_available_food_ui import Ui_AddAvailableFoodWidget
from .creation_utilsateur_ui import Ui_FormCreationCompte